passes/urls.py
"""
Copyright (C) 2017-2018 Pavel Dyachek GPL 3.0+

This file is part of PassHolder.

    PassHolder is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    PassHolder is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with PassHolder.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls import url, include
import django
from django.contrib.auth import views
from . import views

app_name = 'passes'
urlpatterns = [
    url(r'^password_reset/$', 
        django.contrib.auth.views.password_reset, 
        {'post_reset_redirect' : '/password_reset/done/',
         'template_name': 'registration/password_reset.html'},
        name='password_reset'),
    url(r'^password_reset/done/$',
        django.contrib.auth.views.password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        django.contrib.auth.views.password_reset_confirm, 
        {'post_reset_redirect' : '/reset/done/',
         'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', 
        django.contrib.auth.views.password_reset_complete,
        {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
    url(r'^$', views.index, name='index'),
    url(r'^add_info/$', views.add_info, name='add_info'),
    url(r'^get_info/$', views.get_info, name='get_info'),
    url(r'^reg/$', views.reg, name='reg'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^auth/$', views.auth, name='auth'),
    url(r'^logout/$', views.logoutview, name='logout'),
    url(r'^confirmation/$', views.confirmation, name='confirmation'),
    url(r'^ajax/json/$', views.get_json),
    url(r'^delete_info/$', views.delete_info, name='delete_info'),
    url(r'^download_info/&', views.download_info, name='download_info'),
    url(r'^userpage/$', views.userpage, name='userpage'),
    url(r'^email_confirm/$', views.email_confirm, name='email_confirm'),
]

passholder/urls.py
"""
Copyright (C) 2017-2018 Pavel Dyachek GPL 3.0+

This file is part of PassHolder.

    PassHolder is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    PassHolder is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with PassHolder.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('passes.urls')),
    url(r'^admin/', admin.site.urls),
]

passes/forms.py
"""
Copyright (C) 2017-2018 Pavel Dyachek GPL 3.0+

This file is part of PassHolder.

    PassHolder is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    PassHolder is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with PassHolder.  If not, see <http://www.gnu.org/licenses/>.
"""
from django import forms


class PassForm(forms.Form):
    source_text = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Ресурс'}))
    login_text = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Логин'}))
    password_text = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))


class RegForm(forms.Form):
    login = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Логин'}), min_length=5)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}),
                               min_length=8)
    password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль'}),
                                min_length=8)
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Эл. почта'}))


class AuthForm(forms.Form):
    login = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Логин'}))
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))


class FindForm(forms.Form):
    source = forms.CharField(max_length=100, required=False,
                             widget=forms.TextInput(attrs={'placeholder': 'Поиск по ресурсу'}))
    login = forms.CharField(max_length=100, required=False,
                            widget=forms.TextInput(attrs={'placeholder': 'Поиск по логину'}))


class ChangePassForm(forms.Form):
    passwordold = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder': 'Прежний пароль'}))
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder': 'Новый пароль'}),
                               min_length=8)
    password2 = forms.CharField(max_length=100,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Повторите новый пароль'}),
                                min_length=8)

class ConfirmationForm(forms.Form):
    token = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите токен'}))

passes/views.py
"""
Copyright (C) 2017-2018 Pavel Dyachek GPL 3.0+

This file is part of PassHolder.

    PassHolder is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    PassHolder is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with PassHolder.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.shortcuts import render, redirect
from Crypto.Cipher import AES
from .models import Pass_info, Crypto, Confirmation
from .forms import PassForm, RegForm, AuthForm, FindForm, ChangePassForm, ConfirmationForm
from django.db import IntegrityError
from django.utils import timezone
from django.conf import settings
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.hashers import check_password
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from random import randint

class Cred():
    def __init__(self, s, l, i, si):
        self.source = s
        self.login = l
        self.id = i
        self.showid = si


def index(request):
    return render(request, 'passes/index.html', {'title': 'PassHolder'})


def get_json(request):
    credid = request.GET['id']
    try:
        cred = Pass_info.objects.get(id=credid)
        if request.user.id == cred.userid:
            c = Crypto.objects.get(id=cred.crypto_id)
            cipher = AES.new(settings.AES_KEY, AES.MODE_EAX, nonce=c.nonce_p)
            password = cipher.decrypt(cred.password_text)
            try:
                cipher.verify(c.tag_p)
                password_r = password
            except ValueError:
                password_r = 'error'
        else:
            password_r = "error"
        if request.GET['cont'] == "Скрыть":
            return JsonResponse({"password": "",
                                 "id": str(credid),
                                 "show": "Показать"})
        else:
            return JsonResponse({"password": password_r.decode("utf-8"),
                                 "id": str(credid),
                                 "show": "Скрыть"})
    except:
        return JsonResponse({"password": "",
                             "id": str(credid),
                             "show": "Показать", })


@login_required(login_url='/auth/')
def add_info(request):
    if request.method == 'POST':
        form = PassForm(request.POST)
        if form.is_valid():
            sourceb = bytes(form.cleaned_data['source_text'], 'utf-8')
            cipher = AES.new(settings.AES_KEY, AES.MODE_EAX)
            s_nonce = cipher.nonce
            source, s_tag = cipher.encrypt_and_digest(sourceb)

            loginb = bytes(form.cleaned_data['login_text'], 'utf-8')
            cipher = AES.new(settings.AES_KEY, AES.MODE_EAX)
            l_nonce = cipher.nonce
            login, l_tag = cipher.encrypt_and_digest(loginb)

            passwordb = bytes(form.cleaned_data['password_text'], 'utf-8')
            cipher = AES.new(settings.AES_KEY, AES.MODE_EAX)
            p_nonce = cipher.nonce
            password, p_tag = cipher.encrypt_and_digest(passwordb)

            cr = Crypto(
                tag_s=s_tag,
                nonce_s=s_nonce,
                tag_l=l_tag,
                nonce_l=l_nonce,
                tag_p=p_tag,
                nonce_p=p_nonce,
                cr_date=timezone.now())
            cr.save()

            us = Pass_info(
                source_text=source,
                login_text=login,
                password_text=password,
                crypto=Crypto.objects.latest("cr_date"),
                userid=request.user.id)
            us.save()
            return render(request, 'passes/add_info.html', {'form': PassForm(),
                                                            'title': 'Добавление записи',
                                                            'msg': "Успешно добавлено."})
    else:
        form = PassForm()
    return render(request, 'passes/add_info.html', {'form': form,
                                                    'title': 'Добавление записи'})


@login_required(login_url='/auth/')
def get_info(request):
    cred = Pass_info.objects.filter(userid=request.user.id)
    out = []
    for q in cred:
        c = Crypto.objects.get(id=q.crypto_id)
        cipher = AES.new(settings.AES_KEY, AES.MODE_EAX, nonce=c.nonce_s)
        source = cipher.decrypt(q.source_text)
        try:
            cipher.verify(c.tag_s)
            source_r = source
        except ValueError:
            source_r = 'error'

        cipher = AES.new(settings.AES_KEY, AES.MODE_EAX, nonce=c.nonce_l)
        login = cipher.decrypt(q.login_text)
        try:
            cipher.verify(c.tag_l)
            login_r = login
        except ValueError:
            login_r = 'error'

        out.append(Cred(source_r, login_r, q.id, "showid" + str(q.id)))
    sortedout = out
    l = ""
    s = ""
    if request.method == 'POST':
        form = FindForm(request.POST)
        if form.is_valid():
            sortedout = []
            l = form.cleaned_data['login']
            s = form.cleaned_data['source']
            if l and s:
                for cr in out:
                    if str(cr.login).find(l) + 1 and str(cr.source).find(s) + 1:
                        sortedout.append(cr)
            elif l:
                for cr in out:
                    if str(cr.login).find(l) + 1:
                        sortedout.append(cr)
            elif s:
                for cr in out:
                    if str(cr.source).find(s) + 1:
                        sortedout.append(cr)
            else:
                sortedout = out
    else:
        form = FindForm()

    pagin = Paginator(sortedout, 10, orphans=3)
    page = request.GET.get('page')
    try:
        sortedout = pagin.page(page)
    except PageNotAnInteger:
        sortedout = pagin.page(1)
        page = 1
    except EmptyPage:
        sortedoutt = pagin.page(pagin.num_pages)
        page = pagin.num_pages
    return render(request, 'passes/get_info.html', {'curpage': page,
                                                    'form': form,
                                                    'out': sortedout,
                                                    's': s,
                                                    'l': l,
                                                    'title': 'Просмотр записей'})


@login_required(login_url='/auth/')
def delete_info(request):
    credid = request.GET['id']
    try:
        cred = Pass_info.objects.get(id=credid)
        if request.user.id == cred.userid:
            c = Crypto.objects.get(id=cred.crypto_id)
            cipher = AES.new(settings.AES_KEY, AES.MODE_EAX, nonce=c.nonce_s)
            source = cipher.decrypt(cred.source_text)
            try:
                cipher.verify(c.tag_s)
                source_r = source
            except ValueError:
                source_r = 'error'

            cipher = AES.new(settings.AES_KEY, AES.MODE_EAX, nonce=c.nonce_l)
            login = cipher.decrypt(cred.login_text)
            try:
                cipher.verify(c.tag_l)
                login_r = login
            except ValueError:
                login_r = 'error'
            if request.GET['del'] == 'no':
                return render(request, 'passes/delete_info.html', {'source': source_r,
                                                                   'login': login_r,
                                                                   'id': credid,
                                                                   'del': 0,
                                                                   'title': 'Удаление записи'})
            elif request.GET['del'] == 'yes':
                c.delete()
                cred.delete()
                return render(request, 'passes/delete_info.html', {'source': source_r,
                                                                   'login': login_r,
                                                                   'del': 1,
                                                                   'title': 'Удаление записи'})
        return render(request, 'passes/delete_info.html', {'del': 2,
                                                           'title': 'Удаление записи'})
    except:
        return render(request, 'passes/delete_info.html', {'del': 2,
                                                           'title': 'Удаление записи'})


@login_required(login_url='/auth/')
def download_info(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="%s.csv"' % request.user.username
    response.write('Ресурс;Логин;Пароль\n')
    cred = Pass_info.objects.filter(userid=request.user.id)
    out = []
    for q in cred:
        c = Crypto.objects.get(id=q.crypto_id)
        cipher = AES.new(settings.AES_KEY, AES.MODE_EAX, nonce=c.nonce_s)
        source = cipher.decrypt(q.source_text)
        try:
            cipher.verify(c.tag_s)
            source_r = source
        except ValueError:

passes/templates/passes/activate_email.html
{% autoescape off %}
Здравствуй {{ user.username }},
Чтобы завершить регистрацию, перейдите по ссылке ниже,

http://{{ domain }}{% url 'passes:activate' uidb64=uid token=token %}

Если ссылка не работает, скопируйте и вставьте ее в новое окно браузера.

PassHolder
{% endautoescape %}

passes/templates/passes/auth.html
<!--
Copyright (C) 2017-2018 Pavel Dyachek GPL 3.0+

This file is part of PassHolder.

    PassHolder is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    PassHolder is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with PassHolder.  If not, see <http://www.gnu.org/licenses/>.
-->
{% extends "base.html" %}
{% block content %}
<div class="content">
    <div class="mid">
        <div class="boxc" align="center">
            <div class="FieldWrapper"><h4>Вход в аккаунт</h4></div>
            <form action="{% url 'passes:auth'%}" method="post">
            {% csrf_token %}
                <div class="FieldWrapper">
                    {{ form.login }}
                </div>
                <div class="FieldWrapper">
                    {{ form.password }}
                </div>
                <div class="FieldWrapper">
                    <input type="submit" value="Готово"/>
                </div>
                <div class="FieldWrapper">
                    <a href="{% url 'passes:password_reset' %}">Забыли пароль?</a>
                </div>
                {% if errormsg %}
                    <div class="err">{{errormsg}}</div>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

passes/templates/passes/delete_info.html
<!--
Copyright (C) 2017-2018 Pavel Dyachek GPL 3.0+

This file is part of PassHolder.

    PassHolder is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    PassHolder is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with PassHolder.  If not, see <http://www.gnu.org/licenses/>.
-->
{% extends "base.html" %}
{% block content %}
<div class="content">
    {% if del == 0 %}
        <div class="mid">
            <div class="boxc">
                <div class="FieldWrapper">Вы собираетесь удалить запись, расположенную на ресурсе {{source}} с логином {{login}}. вы уверены?</div>
                <div class="FieldWrapper" align="center"><a href="{% url 'passes:delete_info'%}?id={{ id }}&del=yes">Да</a></div>
                <div class="FieldWrapper" align="center"><a href="{% url 'passes:get_info'%}">Нет</a></div>
            </div>            
        </div>
    {% endif %}
    {% if del == 1 %}
        <div class="mid">
            <div class="boxc">
                <div class="FieldWrapper">Запись, расположенная на ресурсе {{source}} с логином {{login}} успешно удалена.</div>
                <div class="FieldWrapper"><a href="{% url 'passes:get_info'%}">Вернуться на страницу просмотра вашей информации.</a></div>
            </div>            
        </div>
    {% endif %}
    {% if del == 2 %}
        <div class="mid">
            <div class="boxc">
                <div class="FieldWrapper">Что-то не так. <a href="{% url 'passes:get_info'%}">Вернуться на страницу просмотра вашей информации.</a></div>
            </div>            
        </div>
    {% endif %}
</div>
{% endblock %}

passes/templates/passes/get_info.html
<!--
Copyright (C) 2017-2018 Pavel Dyachek GPL 3.0+

This file is part of PassHolder.

    PassHolder is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    PassHolder is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with PassHolder.  If not, see <http://www.gnu.org/licenses/>.
-->
<html lang="ru">
    <head>
        {% load static %}
        <meta http-equiv="Content-Type"
              content="text/html; charset=windows-1251">
        <meta name=viewport content="width=500">
        <link rel="stylesheet" type="text/css" href="{% static "main.css" %}">
        <script src="{% static "showpass.js" %}"></script>
        <title>{{title}}</title>
    </head>
    <body>
        <div class="topdiv">
            <ul class="menutxt">
                <a href="{% url 'passes:index'%}"><li>PassHolder</li></a>
                {% if request.user.is_authenticated %}
                <a href="{% url 'passes:add_info'%}"><li>Добавить&nbsp;запись</li></a>
                <a href="{% url 'passes:get_info'%}"><li>Просмотреть&nbsp;записи</li></a>
                {% endif %}    
            </ul>
            <ul class="authtxt">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'passes:userpage'%}"><li>Личный кабинет</li></a>
                    <a href="{% url 'passes:logout'%}"><li>Выйти</li></a>
                {% else %}
                    <a href="{% url 'passes:reg'%}"><li>Регистрация</li></a>
                    <a href="{% url 'passes:auth'%}"><li>Войти</li></a>
                {% endif %}
            </ul>
            <ul class="menuimg">
                <a href="{% url 'passes:index'%}" class="img"><li><img src="{% static "log.png" %}" class="menu"></li></a>
                {% if request.user.is_authenticated %}
                <a href="{% url 'passes:add_info'%}" class="img"><li><img src="{% static "add.png" %}" class="menu"></li></a>
                <a href="{% url 'passes:get_info'%}" class="img"><li><img src="{% static "get.png" %}" class="menu"></li></a>
                {% endif %}    
            </ul>
            {% if request.user.is_authenticated %}
                <ul class="authimg">
                    <a href="{% url 'passes:userpage'%}"><li><img src="{% static "user.png" %}" class="menu"></li></a>
                    <a href="{% url 'passes:logout'%}"><li><img src="{% static "exit.png" %}" class="menu"></li></a>
                </ul>
            {% else %}
                <ul class="menutxtnoauth">
                    <a href="{% url 'passes:reg'%}"><li>Регистрация</li></a>
                    <a href="{% url 'passes:auth'%}"><li>Войти</li></a>
                </ul>
            {% endif %}
        </div>
        <div class="content">
            {% if out %}
                <div class="center">   
                <div class="boxr">
                    <div class="FieldWrapper"><h4>Поиск по записям</h4></div>
                    <form action="{% url 'passes:get_info'%}" method="post">
                        {% csrf_token %}
                        <div class="FieldWrapper">
                            {{ form.source }}
                        </div>
                        <div class="FieldWrapper">
                            {{ form.login }}
                        </div>
                        <div class="FieldWrapper" align="center">
                            <input type="submit" value="Найти"/>
                        </div>
                    </form>
                </div>
                </div>
                <div class="center">
                <div class="box" align="center">
                    <div class="FieldWrapper" align="center">
                        <table class="info" cellspacing="0px" cellpadding="5px">
                            <tr>
                                <td align="center">Ресурс</td>
                                <td align="center">Логин</td>
                                <td align="center">Пароль</td>
                                <td align="center">Показать пароль</td>
                                <td align="center">Удалить запись</td>
                            </tr>
                            {% for i in out %}
                            <tr>
                                <td align="center">{{ i.source }}</td>
                                <td align="center">{{ i.login }}</td>
                                <td align="center"><p id={{ i.id }}></td>
                                <td align="center"><a href="#" onclick="req_ajax_json('{{ i.id }}');" id={{ i.showid }}>Показать</a></td>
                                <td align="center"><a href="{% url 'passes:delete_info'%}?id={{ i.id }}&del=no">Удалить</a></td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                    {% if curpage == 1 and not out.has_next %}
                    {% else %}
                        <div class="FieldWrapper" align="center">
                            {% if out.has_previous %}
                                <span class="pagination"><a href="?page={{ out.previous_page_number }}">&lt;</a></span>
                            {% endif %}
            
                            {% for page in out.paginator.page_range %}
                                {% if page == out.number %}
                                    <span class="pagination">{{ page }}</span>
                                {% else %}
                                    <span class="pagination"><a href="?page={{ page }}">{{ page }}</a></span>
                                {% endif %}
                            {% endfor %}
        
                            {% if out.has_next %}
                                <span class="pagination"><a href="?page={{ out.next_page_number }}">&gt;</a></span>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
                </div>
                <div class="FieldWrapper"><a href="{% url 'passes:download_info'%}?source={{ s }}&login={{ l }}">Скачать csv файл с текущей информацией</a></div>
            {% else %}
                <div class="FieldWrapper">Здесь пусто... <a href="{% url 'passes:add_info'%}">Добавить</a> записи?</div>
            {% endif %}
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.js"
                integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
                crossorigin="anonymous">
        </script>
    </body>
</html>

passes/templates/passes/index.html
<!--
Copyright (C) 2017-2018 Pavel Dyachek GPL 3.0+

This file is part of PassHolder.

    PassHolder is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    PassHolder is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with PassHolder.  If not, see <http://www.gnu.org/licenses/>.
-->
<html lang="ru">
    <head>
        {% load static %}
        <meta http-equiv="Content-Type"
              content="text/html; charset=windows-1251">
        <meta name=viewport content="width=500">
        <link rel="stylesheet" type="text/css" href="{% static "main.css" %}">
        <title>{{title}}</title>
    </head>
    <body>
    <div>
        <div class="topdiv">
            <ul class="menutxt">
                <a href="{% url 'passes:index'%}"><li>PassHolder</li></a>
                {% if request.user.is_authenticated %}
                <a href="{% url 'passes:add_info'%}"><li>Добавить&nbsp;запись</li></a>
                <a href="{% url 'passes:get_info'%}"><li>Просмотреть&nbsp;записи</li></a>
                {% endif %}    
            </ul>
            <ul class="authtxt">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'passes:userpage'%}"><li>Личный кабинет</li></a>
                    <a href="{% url 'passes:logout'%}"><li>Выйти</li></a>
                {% else %}
                    <a href="{% url 'passes:reg'%}"><li>Регистрация</li></a>
                    <a href="{% url 'passes:auth'%}"><li>Войти</li></a>
                {% endif %}
            </ul>
            <ul class="menuimg">
                <a href="{% url 'passes:index'%}" class="img"><li><img src="{% static "log.png" %}" class="menu"></li></a>
                {% if request.user.is_authenticated %}
                <a href="{% url 'passes:add_info'%}" class="img"><li><img src="{% static "add.png" %}" class="menu"></li></a>
                <a href="{% url 'passes:get_info'%}" class="img"><li><img src="{% static "get.png" %}" class="menu"></li></a>
                {% endif %}    
            </ul>
            {% if request.user.is_authenticated %}
                <ul class="authimg">
                    <a href="{% url 'passes:userpage'%}"><li><img src="{% static "user.png" %}" class="menu"></li></a>
                    <a href="{% url 'passes:logout'%}"><li><img src="{% static "exit.png" %}" class="menu"></li></a>
                </ul>
            {% else %}
                <ul class="menutxtnoauth">
                    <a href="{% url 'passes:reg'%}"><li>Регистрация</li></a>
                    <a href="{% url 'passes:auth'%}"><li>Войти</li></a>
                </ul>
            {% endif %}
        </div>
    <div class="land">
        <h1 align="center" class="title">PassHolder</h1>
        <h3 align="center">Храните ваши пароли в облаке, получая доступ к ним из любой точки мира.</h3>
        <div class="mid">
            <a href="{% url 'passes:reg'%}" class="button"><div class="button">Приступить к работе</div></a>
        </div>
    </div>
    <div class="mid"><div class="feature">Возможность пользоваться вашими данными с любого устройства</div></div>
    <hr class="feature">
    <div class="mid"><div class="feature">Хранение данных с тремя параметрами: ресурс, логин, пароль</div></div>
    <hr class="feature">
    <div class="mid"><div class="feature">Поиск нужных записей по логину и/или ресурсу</div></div>
    <hr class="feature">
    <div class="mid"><div class="feature">Экспорт данных в csv файл</div></div>
    </div>
    <div class="footer">&copy; Павел Дьячек. <a href="https://gitlab.com/Janb0t/Passholder">Исходный код</a> проекта в gitlab</div>
    </body>
</html>